import type { Metadata } from "next";
import "./globals.css";
import { getFontClass } from "@/configs/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontClass = getFontClass();

  return (
    <html lang="en">
      <body className={fontClass}>{children}</body>
    </html>
  );
}
